"use client";
import React, { useState, useEffect, useRef, useMemo } from 'react';
import { readExcelFile, validateUrls } from '../utils/excel';

function saveScrapeResults(batchId: string, type: 'old' | 'new', results: any[]) {
  if (!batchId) return;
  localStorage.setItem(`scrape_${batchId}_${type}`, JSON.stringify(results));
}
function loadScrapeResults(batchId: string, type: 'old' | 'new') {
  if (!batchId) return [];
  try {
    return JSON.parse(localStorage.getItem(`scrape_${batchId}_${type}`) || '[]');
  } catch {
    return [];
  }
}

function generateHtaccess(redirects: any[]): string {
  return `# 301 Redirects for SEO Relaunch\n# Generated by SEO Redirect Generator\n\n` +
    redirects.map((r) => `Redirect 301 ${r.old_url} ${r.new_url}`).join("\n");
}
function generateNginx(redirects: any[]): string {
  return `# 301 Redirects for SEO Relaunch\n# Generated by SEO Redirect Generator\n\n` +
    redirects.map((r) => `rewrite ^${r.old_url}$ ${r.new_url} permanent;`).join("\n");
}
function generateCSV(redirects: any[]): string {
  return 'Old URL,New URL,Confidence,Method\n' +
    redirects.map((r) => `${r.old_url},${r.new_url},${Math.round((r.confidence_score || 0) * 100)}%,${r.match_type || 'ai'}`).join("\n");
}

export default function TestPipeline() {
  const [oldUrls, setOldUrls] = useState('https://example.com/old-1\nhttps://example.com/old-2');
  const [newUrls, setNewUrls] = useState('https://example.com/new-1\nhttps://example.com/new-2');
  const [log, setLog] = useState<string[]>([]);
  const [redirects, setRedirects] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [maxRows, setMaxRows] = useState<number>(2);
  const [analysis, setAnalysis] = useState<any[]>([]);
  const [analysisOld, setAnalysisOld] = useState<any[]>([]);
  const [analysisNew, setAnalysisNew] = useState<any[]>([]);
  const [showAnalysis, setShowAnalysis] = useState(false);
  const [oldUploadStatus, setOldUploadStatus] = useState<string>('');
  const [newUploadStatus, setNewUploadStatus] = useState<string>('');
  const [scrapeProgress, setScrapeProgress] = useState({ old: 0, new: 0 });
  const [scrapeTotal, setScrapeTotal] = useState({ old: 0, new: 0 });
  const [scrapeEta, setScrapeEta] = useState<number | null>(null);
  const [scraping, setScraping] = useState(false);
  const scrapeStartRef = useRef<number>(0);
  const [resultTab, setResultTab] = useState<'htaccess'|'nginx'|'csv'>('htaccess');
  const [showResults, setShowResults] = useState(false);

  const oldUrlList = oldUrls.split('\n').map(u => u.trim()).filter(Boolean);
  const newUrlList = newUrls.split('\n').map(u => u.trim()).filter(Boolean);

  const appendLog = (msg: string) => setLog(l => [...l, msg]);

  async function handleExcelUpload(e: React.ChangeEvent<HTMLInputElement>, type: 'old' | 'new') {
    const file = e.target.files?.[0];
    if (!file) return;
    try {
      if (type === 'old') setOldUploadStatus('Lade...');
      if (type === 'new') setNewUploadStatus('Lade...');
      const urls = validateUrls(await readExcelFile(file));
      if (type === 'old') {
        setOldUrls(urls.join('\n'));
        setOldUploadStatus('Erfolgreich geladen!');
      } else {
        setNewUrls(urls.join('\n'));
        setNewUploadStatus('Erfolgreich geladen!');
      }
    } catch {
      if (type === 'old') setOldUploadStatus('Fehler beim Laden!');
      if (type === 'new') setNewUploadStatus('Fehler beim Laden!');
    }
    setTimeout(() => {
      setOldUploadStatus('');
      setNewUploadStatus('');
    }, 2000);
  }

  async function runPipeline() {
    setLog([]);
    setRedirects([]);
    setAnalysis([]);
    setAnalysisOld([]);
    setAnalysisNew([]);
    setShowAnalysis(false);
    setScrapeProgress({ old: 0, new: 0 });
    setScrapeTotal({ old: oldUrlList.length, new: newUrlList.length });
    setScrapeEta(null);
    setScraping(true);
    scrapeStartRef.current = Date.now();
    setLoading(true);
    try {
      appendLog('1. Batch anlegen...');
      const batchRes = await fetch('/api/batch', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          batchName: 'Test-Batch ' + new Date().toISOString(),
          oldUrls: oldUrlList,
          newUrls: newUrlList,
        })
      });
      const batchData = await batchRes.json();
      appendLog('Batch: ' + JSON.stringify(batchData));
      if (!batchData.batchId) throw new Error('Batch creation failed');
      const batchId = batchData.batchId;

      // Scraping-Queue für alt & neu
      async function scrapeQueue(urls: string[], type: 'old' | 'new', concurrency = 2) {
        let results = loadScrapeResults(batchId, type);
        let done = results.length;
        setScrapeProgress(p => ({ ...p, [type]: done }));
        setScrapeTotal(t => ({ ...t, [type]: urls.length }));
        const queue = urls.map((url, i) => ({ url, i }));
        let idx = done;
        let running = 0;
        let etaInterval: any = null;
        function updateEta() {
          const elapsed = (Date.now() - scrapeStartRef.current) / 1000;
          const left = urls.length - done;
          if (done > 0 && left > 0) {
            const avg = elapsed / done;
            setScrapeEta(Math.round(avg * left));
          } else {
            setScrapeEta(null);
          }
        }
        etaInterval = setInterval(updateEta, 1000);
        return new Promise<any[]>(resolve => {
          async function next() {
            if (done >= urls.length) {
              clearInterval(etaInterval);
              resolve(results);
              return;
            }
            while (running < concurrency && idx < urls.length) {
              const { url, i } = queue[idx++];
              running++;
              (async () => {
                const res = await fetch('/api/scrape', {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json' },
                  body: JSON.stringify({ url })
                });
                const data = await res.json();
                results[i] = data;
                saveScrapeResults(batchId, type, results);
                done++;
                setScrapeProgress(p => ({ ...p, [type]: done }));
                setAnalysisOld(type === 'old' ? [...results] : a => a);
                setAnalysisNew(type === 'new' ? [...results] : a => a);
                updateEta();
                running--;
                setTimeout(next, 1200); // 1.2s Pause
              })();
            }
          }
          next();
        });
      }

      appendLog('2. Scraping...');
      // Scrape alt & neu parallel (jeweils mit concurrency=2)
      const [oldResults, newResults] = await Promise.all([
        scrapeQueue(oldUrlList, 'old', 2),
        scrapeQueue(newUrlList, 'new', 2),
      ]);
      setAnalysisOld(oldResults);
      setAnalysisNew(newResults);
      setScraping(false);
      setShowAnalysis(true);
      appendLog('Scrape abgeschlossen.');

      appendLog('3. Matching...');
      const matchRes = await fetch('/api/match', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ batchId })
      });
      const matchData = await matchRes.json();
      appendLog('Match: ' + JSON.stringify(matchData));
      if (!matchData.success) throw new Error('Matching failed');

      appendLog('4. Redirects abfragen...');
      const redirectsRes = await fetch(`/api/redirects?batchId=${batchId}`);
      const redirectsData = await redirectsRes.json();
      setRedirects(redirectsData.data || []);
      appendLog('Redirects: ' + JSON.stringify(redirectsData.data || []));
    } catch (e: any) {
      appendLog('Fehler: ' + e.message);
    } finally {
      setLoading(false);
      setScraping(false);
      setScrapeEta(null);
    }
  }

  // Nach Matching: Redirects laden und Results anzeigen
  useEffect(() => {
    if (!showAnalysis || !log.some(l => l.includes('Match:'))) return;
    // Hole Redirects
    (async () => {
      const lastBatchId = log.find(l => l.includes('Batch:'))?.match(/"batchId":"([^"]+)"/i)?.[1];
      if (!lastBatchId) return;
      const res = await fetch(`/api/redirects?batchId=${lastBatchId}`);
      const data = await res.json();
      setRedirects(data.data || []);
      setShowResults(true);
    })();
  }, [showAnalysis, log]);

  // Stats für Ergebnis-Screen
  const stats = useMemo(() => {
    const total = redirects.length;
    const ai = redirects.filter(r => r.match_type === 'ai').length;
    const confidence = redirects.length ? Math.round(redirects.reduce((acc, r) => acc + (r.confidence_score || 0), 0) / redirects.length * 100) : 0;
    return { total, ai, confidence };
  }, [redirects]);

  // Export-Strings
  const exports = useMemo(() => ({
    htaccess: generateHtaccess(redirects),
    nginx: generateNginx(redirects),
    csv: generateCSV(redirects),
  }), [redirects]);

  return (
    <div style={{ width: '100vw', minHeight: '100vh', background: '#fff', padding: 0, margin: 0, boxSizing: 'border-box' }}>
      <h2 style={{ fontSize: 32, fontWeight: 800, margin: '32px 0 24px 0', textAlign: 'center', letterSpacing: '-1px' }}>Backend-Pipeline Test</h2>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 0, width: '100vw' }}>
        <div style={{ flex: 1, minWidth: 0, padding: 0 }}>
          <label style={{ fontWeight: 600, marginLeft: 24 }}>Alte URLs (eine pro Zeile):</label>
          <input type="file" accept=".xlsx,.xls,.csv" style={{ margin: '8px 0 8px 24px' }} onChange={e => handleExcelUpload(e, 'old')} />
          {oldUploadStatus && <span style={{ color: oldUploadStatus.includes('Fehler') ? '#ef4444' : '#10b981', marginLeft: 12 }}>{oldUploadStatus}</span>}
          <textarea rows={12} style={{ width: '100%', fontFamily: 'monospace', fontSize: 18, border: 'none', borderBottom: '2px solid #6366f1', borderRadius: 0, padding: 16, marginBottom: 8, background: '#f3f4f6', boxSizing: 'border-box', resize: 'vertical', minHeight: 180, maxHeight: 400, overflowY: 'auto' }} value={oldUrls} onChange={e => setOldUrls(e.target.value)} />
          <div style={{ color: '#6366f1', fontWeight: 500, marginBottom: 8, marginLeft: 24 }}>{oldUrlList.length} URLs importiert</div>
          <div style={{ background: '#f3f4f6', padding: 8, maxHeight: 180, overflowY: 'auto', fontFamily: 'monospace', fontSize: 16, width: '100%', borderRadius: 0, borderLeft: '4px solid #6366f1', boxSizing: 'border-box' }}>
            {oldUrlList.map((url, i) => <div key={i} style={{ whiteSpace: 'pre', overflowX: 'auto', fontSize: 16 }}>{url}</div>)}
          </div>
        </div>
        <div style={{ flex: 1, minWidth: 0, padding: 0 }}>
          <label style={{ fontWeight: 600, marginLeft: 24 }}>Neue URLs (eine pro Zeile):</label>
          <input type="file" accept=".xlsx,.xls,.csv" style={{ margin: '8px 0 8px 24px' }} onChange={e => handleExcelUpload(e, 'new')} />
          {newUploadStatus && <span style={{ color: newUploadStatus.includes('Fehler') ? '#ef4444' : '#10b981', marginLeft: 12 }}>{newUploadStatus}</span>}
          <textarea rows={12} style={{ width: '100%', fontFamily: 'monospace', fontSize: 18, border: 'none', borderBottom: '2px solid #ec4899', borderRadius: 0, padding: 16, marginBottom: 8, background: '#f3f4f6', boxSizing: 'border-box', resize: 'vertical', minHeight: 180, maxHeight: 400, overflowY: 'auto' }} value={newUrls} onChange={e => setNewUrls(e.target.value)} />
          <div style={{ color: '#ec4899', fontWeight: 500, marginBottom: 8, marginLeft: 24 }}>{newUrlList.length} URLs importiert</div>
          <div style={{ background: '#f3f4f6', padding: 8, maxHeight: 180, overflowY: 'auto', fontFamily: 'monospace', fontSize: 16, width: '100%', borderRadius: 0, borderLeft: '4px solid #ec4899', boxSizing: 'border-box' }}>
            {newUrlList.map((url, i) => <div key={i} style={{ whiteSpace: 'pre', overflowX: 'auto', fontSize: 16 }}>{url}</div>)}
          </div>
        </div>
      </div>
      <div style={{ margin: '32px 0 24px 0', width: '100vw', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <label style={{ fontWeight: 600, marginRight: 12 }}>Analysiere die ersten</label>
        <input type="number" min={1} max={oldUrlList.length} value={maxRows} onChange={e => setMaxRows(Number(e.target.value))} style={{ width: 80, fontSize: 18, borderRadius: 6, padding: 6, marginRight: 8, border: '1.5px solid #6366f1' }} />
        <span style={{ color: '#6b7280', fontSize: 18 }}>Seiten</span>
      </div>
      <div style={{ width: '100vw', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 32 }}>
        <button onClick={runPipeline} disabled={loading || scraping} style={{ padding: '18px 60px', fontSize: 22, borderRadius: 0, background: 'linear-gradient(90deg,#6366f1,#ec4899)', color: '#fff', border: 'none', fontWeight: 700, letterSpacing: 1, cursor: loading || scraping ? 'not-allowed' : 'pointer', boxShadow: '0 2px 16px #0001' }}>
          {loading || scraping ? 'Bitte warten...' : 'Pipeline testen'}
        </button>
      </div>
      <div style={{ fontFamily: 'monospace', fontSize: 16, background: '#f3f4f6', borderRadius: 0, padding: 18, marginBottom: 24, minHeight: 80, maxHeight: 220, overflowY: 'auto', width: '100vw', boxSizing: 'border-box' }}>
        {log.map((l, i) => <div key={i}>{l}</div>)}
      </div>
      {showAnalysis && (
        <div style={{ marginBottom: 32, width: '100vw', display: 'flex', gap: 32, flexWrap: 'wrap' }}>
          <div style={{ flex: 1, minWidth: 320 }}>
            <h3 style={{ fontSize: 22, fontWeight: 700, margin: '24px 0 12px 0', textAlign: 'center', color: '#6366f1' }}>Analysierte alte URLs (max. {maxRows})</h3>
            <div style={{ background: '#f9fafb', borderRadius: 0, padding: 18, maxHeight: 340, overflowY: 'auto', fontFamily: 'monospace', fontSize: 16, width: '100%', boxSizing: 'border-box' }}>
              {analysisOld.length === 0 ? <div style={{ color: '#ef4444' }}>Keine alten URLs analysiert.</div> : analysisOld.map((u, i) => (
                <div key={u.id || i} style={{ borderBottom: '1px solid #e5e7eb', padding: 10 }}>
                  <div><b>URL:</b> {u.url}</div>
                  <div><b>Status:</b> {u.status_code}</div>
                  <div><b>Titel:</b> {u.title}</div>
                  <div><b>Meta:</b> {u.meta_description}</div>
                  <div><b>H1:</b> {u.h1_heading}</div>
                  <div><b>Main:</b> <span style={{ color: '#64748b' }}>{u.main_content?.slice(0, 200) || ''}{u.main_content && u.main_content.length > 200 ? '…' : ''}</span></div>
                </div>
              ))}
            </div>
          </div>
          <div style={{ flex: 1, minWidth: 320 }}>
            <h3 style={{ fontSize: 22, fontWeight: 700, margin: '24px 0 12px 0', textAlign: 'center', color: '#ec4899' }}>Analysierte neue URLs (max. {maxRows})</h3>
            <div style={{ background: '#f9fafb', borderRadius: 0, padding: 18, maxHeight: 340, overflowY: 'auto', fontFamily: 'monospace', fontSize: 16, width: '100%', boxSizing: 'border-box' }}>
              {analysisNew.length === 0 ? <div style={{ color: '#ef4444' }}>Keine neuen URLs analysiert.</div> : analysisNew.map((u, i) => (
                <div key={u.id || i} style={{ borderBottom: '1px solid #e5e7eb', padding: 10 }}>
                  <div><b>URL:</b> {u.url}</div>
                  <div><b>Status:</b> {u.status_code}</div>
                  <div><b>Titel:</b> {u.title}</div>
                  <div><b>Meta:</b> {u.meta_description}</div>
                  <div><b>H1:</b> {u.h1_heading}</div>
                  <div><b>Main:</b> <span style={{ color: '#64748b' }}>{u.main_content?.slice(0, 200) || ''}{u.main_content && u.main_content.length > 200 ? '…' : ''}</span></div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
      <div style={{ width: '100vw' }}>
        <b style={{ marginLeft: 24 }}>Gefundene Redirects:</b>
        <pre style={{ background: '#111827', color: '#a7f3d0', borderRadius: 0, padding: 16, fontSize: 16, minHeight: 40, maxHeight: 220, overflowY: 'auto', width: '100vw', boxSizing: 'border-box' }}>{JSON.stringify(redirects, null, 2)}</pre>
      </div>
      {(scraping || scrapeProgress.old > 0 || scrapeProgress.new > 0) && (
        <div style={{ width: '100vw', marginBottom: 24, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <div style={{ width: 480, maxWidth: '90vw', background: '#f3f4f6', borderRadius: 16, overflow: 'hidden', marginBottom: 16, border: '2.5px solid #6366f1', boxShadow: '0 2px 16px #6366f122' }}>
            <div style={{ height: 28, background: 'linear-gradient(90deg,#6366f1,#ec4899)', width: `${Math.round(((scrapeProgress.old + scrapeProgress.new) / (scrapeTotal.old + scrapeTotal.new || 1)) * 100)}%`, transition: 'width 0.5s cubic-bezier(.4,2,.6,1)', borderRadius: 16, boxShadow: '0 2px 8px #6366f133', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontWeight: 700, fontSize: 18, letterSpacing: 1 }}>
              {Math.round(((scrapeProgress.old + scrapeProgress.new) / (scrapeTotal.old + scrapeTotal.new || 1)) * 100)}%
            </div>
          </div>
          <div style={{ fontFamily: 'Inter, sans-serif', fontSize: 20, color: '#6366f1', marginBottom: 8, fontWeight: 700, letterSpacing: 0.5 }}>
            Scraping: <span style={{ color: '#111' }}>{scrapeProgress.old + scrapeProgress.new}</span> / {scrapeTotal.old + scrapeTotal.new} Seiten{scrapeEta !== null ? <span style={{ color: '#64748b', fontWeight: 400 }}> (ca. {scrapeEta}s)</span> : ''}
          </div>
          <div style={{ width: '100vw', display: 'flex', gap: 32, justifyContent: 'center', marginTop: 24, flexWrap: 'wrap' }}>
            <div style={{ flex: 1, minWidth: 320, maxWidth: 600 }}>
              <h3 style={{ fontSize: 22, fontWeight: 800, margin: '0 0 16px 0', textAlign: 'center', color: '#6366f1', letterSpacing: -0.5 }}>Analysierte alte URLs</h3>
              <div style={{ background: '#fff', borderRadius: 18, padding: 18, minHeight: 120, boxShadow: '0 2px 16px #6366f122', border: '1.5px solid #e0e7ff', maxHeight: 340, overflowY: 'auto', fontFamily: 'monospace', fontSize: 16, width: '100%', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', gap: 12 }}>
                {analysisOld.length === 0 ? <div style={{ color: '#ef4444', fontWeight: 600 }}>Keine alten URLs analysiert.</div> : analysisOld.map((u, i) => (
                  <div key={u.id || i} style={{ borderBottom: '1px solid #e5e7eb', padding: '10px 0', marginBottom: 2, transition: 'background 0.2s', background: u.error ? '#fef2f2' : 'transparent' }}>
                    <div style={{ fontWeight: 700, color: '#6366f1', fontSize: 15, marginBottom: 2 }}>{u.url}</div>
                    <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', fontSize: 15 }}>
                      <span><b>Status:</b> {u.status_code ?? u.status}</span>
                      <span><b>Titel:</b> {u.title}</span>
                      <span><b>Meta:</b> {u.meta_description}</span>
                      <span><b>H1:</b> {u.h1_heading}</span>
                    </div>
                    <div style={{ color: '#64748b', fontSize: 14, marginTop: 2, whiteSpace: 'pre-line' }}><b>Main:</b> {u.main_content?.slice(0, 200) || ''}{u.main_content && u.main_content.length > 200 ? '…' : ''}</div>
                    {u.error && <div style={{ color: '#ef4444', fontWeight: 600, fontSize: 14, marginTop: 4 }}>Fehler: {u.error}</div>}
                  </div>
                ))}
              </div>
            </div>
            <div style={{ flex: 1, minWidth: 320, maxWidth: 600 }}>
              <h3 style={{ fontSize: 22, fontWeight: 800, margin: '0 0 16px 0', textAlign: 'center', color: '#ec4899', letterSpacing: -0.5 }}>Analysierte neue URLs</h3>
              <div style={{ background: '#fff', borderRadius: 18, padding: 18, minHeight: 120, boxShadow: '0 2px 16px #ec489922', border: '1.5px solid #fce7f3', maxHeight: 340, overflowY: 'auto', fontFamily: 'monospace', fontSize: 16, width: '100%', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', gap: 12 }}>
                {analysisNew.length === 0 ? <div style={{ color: '#ef4444', fontWeight: 600 }}>Keine neuen URLs analysiert.</div> : analysisNew.map((u, i) => (
                  <div key={u.id || i} style={{ borderBottom: '1px solid #e5e7eb', padding: '10px 0', marginBottom: 2, transition: 'background 0.2s', background: u.error ? '#fef2f2' : 'transparent' }}>
                    <div style={{ fontWeight: 700, color: '#ec4899', fontSize: 15, marginBottom: 2 }}>{u.url}</div>
                    <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', fontSize: 15 }}>
                      <span><b>Status:</b> {u.status_code ?? u.status}</span>
                      <span><b>Titel:</b> {u.title}</span>
                      <span><b>Meta:</b> {u.meta_description}</span>
                      <span><b>H1:</b> {u.h1_heading}</span>
                    </div>
                    <div style={{ color: '#64748b', fontSize: 14, marginTop: 2, whiteSpace: 'pre-line' }}><b>Main:</b> {u.main_content?.slice(0, 200) || ''}{u.main_content && u.main_content.length > 200 ? '…' : ''}</div>
                    {u.error && <div style={{ color: '#ef4444', fontWeight: 600, fontSize: 14, marginTop: 4 }}>Fehler: {u.error}</div>}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
      {/* Ergebnis-Screen */}
      {showResults && (
        <div style={{ width: '100vw', margin: '48px 0 0 0', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 32 }}>
          {/* Stats */}
          <div style={{ display: 'flex', gap: 32, marginBottom: 24, flexWrap: 'wrap', justifyContent: 'center' }}>
            <div style={{ background: '#fff', borderRadius: 16, boxShadow: '0 2px 16px #6366f122', border: '2px solid #e0e7ff', padding: '24px 36px', minWidth: 180, textAlign: 'center' }}>
              <div style={{ fontSize: 32, fontWeight: 800, color: '#6366f1', marginBottom: 4 }}>{stats.total}</div>
              <div style={{ fontSize: 16, color: '#64748b', fontWeight: 600 }}>Redirects</div>
            </div>
            <div style={{ background: '#fff', borderRadius: 16, boxShadow: '0 2px 16px #ec489922', border: '2px solid #fce7f3', padding: '24px 36px', minWidth: 180, textAlign: 'center' }}>
              <div style={{ fontSize: 32, fontWeight: 800, color: '#ec4899', marginBottom: 4 }}>{stats.ai}</div>
              <div style={{ fontSize: 16, color: '#64748b', fontWeight: 600 }}>AI-Matches</div>
            </div>
            <div style={{ background: '#fff', borderRadius: 16, boxShadow: '0 2px 16px #10b98122', border: '2px solid #d1fae5', padding: '24px 36px', minWidth: 180, textAlign: 'center' }}>
              <div style={{ fontSize: 32, fontWeight: 800, color: '#10b981', marginBottom: 4 }}>{stats.confidence}%</div>
              <div style={{ fontSize: 16, color: '#64748b', fontWeight: 600 }}>Ø Confidence</div>
            </div>
          </div>
          {/* Export-Box */}
          <div style={{ background: '#fff', borderRadius: 24, boxShadow: '0 2px 24px #6366f122', border: '2px solid #e0e7ff', padding: '32px 24px', width: '100%', maxWidth: 900, marginBottom: 32, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 18 }}>
            <div style={{ display: 'flex', gap: 12, marginBottom: 12 }}>
              {(['htaccess', 'nginx', 'csv'] as const).map(tab => (
                <button key={tab} onClick={() => setResultTab(tab)} style={{
                  padding: '12px 32px', fontSize: 18, fontWeight: 700, borderRadius: 16, border: resultTab === tab ? '2.5px solid #6366f1' : '2px solid #e0e7ff', background: resultTab === tab ? 'linear-gradient(90deg,#6366f1,#ec4899)' : '#f3f4f6', color: resultTab === tab ? '#fff' : '#6366f1', boxShadow: resultTab === tab ? '0 2px 12px #6366f122' : 'none', transition: 'all 0.2s', cursor: 'pointer' }}>
                  {tab === 'htaccess' ? '.htaccess' : tab === 'nginx' ? 'Nginx' : 'CSV/Excel'}
                </button>
              ))}
            </div>
            <pre style={{ background: '#f9fafb', borderRadius: 16, padding: 18, fontSize: 16, width: '100%', minHeight: 120, maxHeight: 260, overflowY: 'auto', color: '#374151', fontFamily: 'monospace', border: '1.5px solid #e0e7ff', marginBottom: 8 }}>{exports[resultTab]}</pre>
            <div style={{ display: 'flex', gap: 16, width: '100%', justifyContent: 'flex-end' }}>
              <button onClick={() => { navigator.clipboard.writeText(exports[resultTab]); }} style={{ padding: '10px 32px', fontSize: 16, borderRadius: 12, background: 'linear-gradient(90deg,#10b981,#6366f1)', color: '#fff', fontWeight: 700, border: 'none', cursor: 'pointer', boxShadow: '0 2px 8px #10b98122' }}>Copy</button>
              <a href={`data:text/plain;charset=utf-8,${encodeURIComponent(exports[resultTab])}`} download={`redirects.${resultTab === 'csv' ? 'csv' : 'txt'}`} style={{ padding: '10px 32px', fontSize: 16, borderRadius: 12, background: 'linear-gradient(90deg,#6366f1,#ec4899)', color: '#fff', fontWeight: 700, border: 'none', textDecoration: 'none', boxShadow: '0 2px 8px #6366f122' }}>Download</a>
            </div>
          </div>
          {/* Detailansicht */}
          <div style={{ width: '100%', maxWidth: 1100, display: 'flex', flexDirection: 'column', gap: 24 }}>
            {redirects.map((r, i) => {
              const oldData = analysisOld.find(u => u.url === r.old_url?.url || u.url === r.old_url);
              const newData = analysisNew.find(u => u.url === r.new_url?.url || u.url === r.new_url);
              return (
                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 0, width: '100%' }}>
                  {/* Alte URL Box */}
                  <div style={{ flex: 1, background: '#f3f4f6', borderRadius: 16, padding: 18, minWidth: 220, boxShadow: '0 2px 8px #6366f122', border: '1.5px solid #e0e7ff', marginRight: 0 }}>
                    <div style={{ fontWeight: 700, color: '#6366f1', fontSize: 15, marginBottom: 2 }}>{oldData?.url || r.old_url?.url || r.old_url}</div>
                    <div style={{ fontSize: 15, color: '#64748b', marginBottom: 2 }}><b>Titel:</b> {oldData?.title}</div>
                    <div style={{ fontSize: 15, color: '#64748b', marginBottom: 2 }}><b>Meta:</b> {oldData?.meta_description}</div>
                    <div style={{ fontSize: 15, color: '#64748b', marginBottom: 2 }}><b>H1:</b> {oldData?.h1_heading}</div>
                    <div style={{ fontSize: 14, color: '#9ca3af', marginBottom: 2 }}><b>Main:</b> {oldData?.main_content?.slice(0, 120) || ''}{oldData?.main_content && oldData.main_content.length > 120 ? '…' : ''}</div>
                  </div>
                  {/* Pfeil */}
                  <div style={{ width: 60, display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%' }}>
                    <div style={{ width: 40, height: 2, background: 'linear-gradient(90deg,#6366f1,#ec4899)', position: 'relative' }}>
                      <div style={{ position: 'absolute', right: -8, top: -6, width: 0, height: 0, borderTop: '8px solid transparent', borderBottom: '8px solid transparent', borderLeft: '16px solid #ec4899' }} />
                    </div>
                  </div>
                  {/* Neue URL Box */}
                  <div style={{ flex: 1, background: '#fff', borderRadius: 16, padding: 18, minWidth: 220, boxShadow: '0 2px 8px #ec489922', border: '1.5px solid #fce7f3', marginLeft: 0 }}>
                    <div style={{ fontWeight: 700, color: '#ec4899', fontSize: 15, marginBottom: 2 }}>{newData?.url || r.new_url?.url || r.new_url}</div>
                    <div style={{ fontSize: 15, color: '#64748b', marginBottom: 2 }}><b>Titel:</b> {newData?.title}</div>
                    <div style={{ fontSize: 15, color: '#64748b', marginBottom: 2 }}><b>Meta:</b> {newData?.meta_description}</div>
                    <div style={{ fontSize: 15, color: '#64748b', marginBottom: 2 }}><b>H1:</b> {newData?.h1_heading}</div>
                    <div style={{ fontSize: 14, color: '#9ca3af', marginBottom: 2 }}><b>Main:</b> {newData?.main_content?.slice(0, 120) || ''}{newData?.main_content && newData.main_content.length > 120 ? '…' : ''}</div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
} 