import React, { useState, useEffect } from 'react';
import { supabase } from '../supabase/client';

type ExportTabKey = 'htaccess' | 'nginx' | 'csv';
type MappingType = 'All' | 'Exact' | 'Fuzzy' | 'Manual' | string;

type Redirect = {
  id: string;
  old_url: { url: string };
  new_url: { url: string };
  confidence_score: number;
  match_type: string;
};

type Batch = { id: string; name: string };

function useCountUp(target: number, duration = 900) {
  const [value, setValue] = useState(0);
  useEffect(() => {
    let start = 0;
    let startTime: number | null = null;
    function animate(ts: number) {
      if (!startTime) startTime = ts;
      const progress = Math.min(1, (ts - startTime) / duration);
      setValue(Math.round(target * progress));
      if (progress < 1) requestAnimationFrame(animate);
    }
    requestAnimationFrame(animate);
    return () => setValue(target);
  }, [target, duration]);
  return value;
}

export function ResultDashboard() {
  const [batches, setBatches] = useState<Batch[]>([]);
  const [selectedBatch, setSelectedBatch] = useState<string | null>(null);
  const [redirects, setRedirects] = useState<Redirect[]>([]);
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<ExportTabKey>('htaccess');
  const [copySuccess, setCopySuccess] = useState(false);
  const [search, setSearch] = useState('');
  const [typeFilter, setTypeFilter] = useState<MappingType>('All');
  const [page, setPage] = useState(1);
  const perPage = 10;
  const [showDebug, setShowDebug] = useState(false);

  // Lade alle Batches beim Mounten
  useEffect(() => {
    (async () => {
      const { data } = await supabase.from('batches').select('id, name').order('created_at', { ascending: false });
      setBatches(data || []);
      if (data && data.length > 0 && !selectedBatch) setSelectedBatch(data[0].id);
    })();
  }, []);

  // Lade Redirects für den gewählten Batch
  useEffect(() => {
    if (!selectedBatch) return;
    setLoading(true);
    (async () => {
      const { data } = await supabase
        .from('redirects')
        .select('id, old_url:old_url_id(url), new_url:new_url_id(url), confidence_score, match_type')
        .eq('batch_id', selectedBatch);
      // Fange Array/Objekt-Relationen ab
      const normalized = (data || []).map((r: any) => ({
        ...r,
        old_url: Array.isArray(r.old_url) ? r.old_url[0] : r.old_url,
        new_url: Array.isArray(r.new_url) ? r.new_url[0] : r.new_url,
      }));
      setRedirects(normalized);
      setLoading(false);
    })();
  }, [selectedBatch]);

  // Stats
  const total = useCountUp(redirects.length);
  const exact = useCountUp(redirects.filter(r => r.match_type === 'exact').length);
  const fuzzy = useCountUp(redirects.filter(r => r.match_type === 'fuzzy').length);
  const manual = useCountUp(redirects.filter(r => r.match_type === 'manual').length);
  const confidence = useCountUp(
    redirects.length ? Math.round(redirects.reduce((acc, r) => acc + (r.confidence_score || 0), 0) / redirects.length * 100) : 0
  );

  // Filter + Pagination
  const mappingTypes: MappingType[] = ['All', 'exact', 'fuzzy', 'manual'];
  const filteredMappings = redirects.filter(m =>
    (typeFilter === 'All' || m.match_type === typeFilter) &&
    (m.old_url?.url?.toLowerCase().includes(search.toLowerCase()) || m.new_url?.url?.toLowerCase().includes(search.toLowerCase()))
  );
  const totalPages = Math.ceil(filteredMappings.length / perPage);
  const pagedMappings = filteredMappings.slice((page - 1) * perPage, page * perPage);
  useEffect(() => { setPage(1); }, [typeFilter, search, selectedBatch]);

  // Export-Generatoren
  function generateHtaccess(redirects: Redirect[]): string {
    return `# 301 Redirects for SEO Relaunch\n# Generated by SEO Redirect Generator\n\n` +
      redirects.map((r) => `Redirect 301 ${r.old_url?.url} ${r.new_url?.url}`).join("\n");
  }
  function generateNginx(redirects: Redirect[]): string {
    return `# 301 Redirects for SEO Relaunch\n# Generated by SEO Redirect Generator\n\n` +
      redirects.map((r) => `rewrite ^${r.old_url?.url}$ ${r.new_url?.url} permanent;`).join("\n");
  }
  function generateCSV(redirects: Redirect[]): string {
    return 'Old URL,New URL,Confidence,Method\n' +
      redirects.map((r) => `${r.old_url?.url},${r.new_url?.url},${Math.round((r.confidence_score || 0) * 100)}%,${r.match_type}`).join("\n");
  }

  const exports = {
    htaccess: generateHtaccess(redirects),
    nginx: generateNginx(redirects),
    csv: generateCSV(redirects),
  };

  const handleCopy = async (text: string) => {
    await navigator.clipboard.writeText(text);
    setCopySuccess(true);
    setTimeout(() => setCopySuccess(false), 1200);
  };

  return (
    <div className="flex flex-col gap-12 py-12 w-full px-0 md:px-0">
      {/* Batch-Selector */}
      <div className="flex flex-wrap items-center gap-4 w-full px-2 md:px-8 mb-4">
        <label className="font-semibold text-slate-700">Batch:</label>
        <select
          className="px-3 py-2 rounded border border-gray-200 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 text-sm"
          value={selectedBatch || ''}
          onChange={e => setSelectedBatch(e.target.value)}
        >
          {batches.map(b => (
            <option key={b.id} value={b.id}>{b.name} ({b.id.slice(0, 6)})</option>
          ))}
        </select>
        {loading && <span className="text-xs text-indigo-500 animate-pulse">Lade Daten…</span>}
      </div>
      {/* Stats-Header */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-6 w-full px-2 md:px-8">
        <StatCard label="Total" value={total} />
        <StatCard label="Exact" value={exact} badge="Exact" icon={<span title="Exakte Matches">✅</span>} />
        <StatCard label="Fuzzy" value={fuzzy} badge="Fuzzy" icon={<span title="Fuzzy Matches">✨</span>} />
        <StatCard label="Manual" value={manual} badge="Manual" icon={<span title="Manuell zugeordnet">🖐️</span>} />
        <StatCard label="Ø Confidence" value={confidence + '%'} confidence={confidence} tooltip="Durchschnittlicher AI-Confidence-Score" />
      </div>
      {/* Export-Tabs */}
      <div className="bg-white rounded-xl shadow p-6 border border-gray-100 w-full px-2 md:px-8">
        <div className="flex gap-4 mb-4 items-end">
          {(['htaccess', 'nginx', 'csv'] as ExportTabKey[]).map(tab => (
            <button
              key={tab}
              className={`px-4 py-2 rounded-t font-medium transition-all duration-150 border-b-2 ${
                activeTab === tab
                  ? 'border-indigo-500 text-indigo-600 bg-indigo-50'
                  : 'border-transparent text-gray-400 hover:text-indigo-500'
              }`}
              onClick={() => setActiveTab(tab)}
            >
              {tab === 'htaccess' ? '.htaccess' : tab === 'nginx' ? 'Nginx' : 'CSV/Excel'}
            </button>
          ))}
          <div className="ml-auto flex gap-2">
            <button
              className={`px-3 py-1 rounded flex items-center gap-1 bg-indigo-100 text-indigo-600 text-xs font-semibold hover:bg-indigo-200 transition ${copySuccess ? 'animate-pulse' : ''}`}
              onClick={() => handleCopy(exports[activeTab])}
              title="In Zwischenablage kopieren"
            >
              {copySuccess ? <span>✔️</span> : <span>📋</span>} Copy
            </button>
            <a
              href={`data:text/plain;charset=utf-8,${encodeURIComponent(exports[activeTab])}`}
              download={`redirects.${activeTab === 'csv' ? 'csv' : 'txt'}`}
              className="px-3 py-1 rounded bg-gray-100 text-gray-500 text-xs font-semibold hover:bg-gray-200 transition"
              title="Datei herunterladen"
            >
              ⬇️ Download
            </a>
          </div>
        </div>
        <div className="text-xs text-gray-400 mb-2">Exportiere deine Redirects für verschiedene Systeme.</div>
        <pre className="bg-gray-50 rounded p-4 text-xs font-mono overflow-x-auto border border-gray-100 transition-all duration-150">
          {exports[activeTab]}
        </pre>
        {copySuccess && <div className="mt-2 text-green-600 text-xs animate-pulse">In Zwischenablage kopiert!</div>}
      </div>
      {/* Mapping-Tabelle */}
      <div className="bg-white rounded-xl shadow p-6 border border-gray-100 w-full px-2 md:px-8">
        <div className="flex flex-wrap items-center mb-4 gap-4">
          <input
            type="text"
            placeholder="Suche alte oder neue URL…"
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="px-3 py-2 rounded border border-gray-200 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 text-sm w-full md:w-72 transition"
          />
          <div className="flex gap-2 flex-wrap">
            {mappingTypes.map(type => (
              <button
                key={type}
                className={`px-3 py-1 rounded-full text-xs font-semibold border transition-all duration-150 ${
                  typeFilter === type
                    ? 'bg-indigo-500 text-white border-indigo-500 shadow'
                    : 'bg-gray-100 text-gray-500 border-gray-200 hover:bg-indigo-50 hover:text-indigo-600'
                }`}
                onClick={() => setTypeFilter(type)}
              >
                {type.charAt(0).toUpperCase() + type.slice(1)}
              </button>
            ))}
          </div>
          <span className="text-xs text-gray-400 ml-auto">{filteredMappings.length} Ergebnisse</span>
        </div>
        <div className="overflow-x-auto max-h-[340px]">
          <table className="min-w-full text-sm sticky-header">
            <thead className="sticky top-0 bg-white z-10 shadow-sm">
              <tr className="text-gray-500 border-b">
                <th className="py-2 px-3 text-left">Alte URL</th>
                <th className="py-2 px-3 text-left">Neue URL</th>
                <th className="py-2 px-3 text-left">Typ</th>
                <th className="py-2 px-3 text-left">Confidence</th>
                <th className="py-2 px-3 text-left">AI</th>
                <th className="py-2 px-3 text-left"></th>
              </tr>
            </thead>
            <tbody>
              {pagedMappings.length === 0 ? (
                <tr>
                  <td colSpan={6} className="py-12 text-center text-gray-400">
                    <div className="flex flex-col items-center gap-2">
                      <span className="text-4xl">🔍</span>
                      <span>Keine Ergebnisse gefunden</span>
                    </div>
                  </td>
                </tr>
              ) : (
                pagedMappings.map((m, i) => (
                  <tr key={i} className="border-b hover:bg-gradient-to-r hover:from-indigo-50 hover:to-pink-50 transition group">
                    <td className="py-2 px-3 font-mono text-indigo-700">{m.old_url?.url}</td>
                    <td className="py-2 px-3 font-mono text-pink-600">{m.new_url?.url}</td>
                    <td className="py-2 px-3">
                      <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-medium
                        ${m.match_type === 'exact' ? 'bg-emerald-100 text-emerald-700' :
                          m.match_type === 'fuzzy' ? 'bg-yellow-100 text-yellow-700' :
                          m.match_type === 'manual' ? 'bg-gray-100 text-gray-500' : 'bg-gray-100 text-gray-500'}
                      `} title={m.match_type === 'exact' ? 'Exaktes Match' : m.match_type === 'fuzzy' ? 'Fuzzy Match' : m.match_type === 'manual' ? 'Manuell zugeordnet' : ''}>
                        {m.match_type === 'exact' ? '✅' : m.match_type === 'fuzzy' ? '✨' : m.match_type === 'manual' ? '🖐️' : ''} {m.match_type}
                      </span>
                    </td>
                    <td className="py-2 px-3">
                      <div className="flex items-center gap-2">
                        <div className="w-16 h-2 bg-gray-200 rounded" title={`AI-Confidence: ${Math.round((m.confidence_score || 0) * 100)}%`}>
                          <div
                            className={`h-2 rounded ${m.confidence_score > 0.9 ? 'bg-emerald-400' : m.confidence_score > 0.8 ? 'bg-yellow-400' : 'bg-gray-400'}`}
                            style={{ width: `${Math.round((m.confidence_score || 0) * 100)}%` }}
                          />
                        </div>
                        <span className="text-xs text-gray-500">{m.confidence_score ? `${Math.round((m.confidence_score || 0) * 100)}%` : '-'}</span>
                      </div>
                    </td>
                    <td className="py-2 px-3">
                      {m.match_type !== 'manual' ? (
                        <span className="inline-flex items-center gap-1 text-indigo-500 text-xs font-semibold" title="AI generiert"><svg width="16" height="16" fill="none"><circle cx="8" cy="8" r="8" fill="#6366f1"/><path d="M8 4v4l2 2" stroke="#fff" strokeWidth="1.5" strokeLinecap="round"/></svg>AI</span>
                      ) : (
                        <span className="inline-flex items-center gap-1 text-gray-400 text-xs font-semibold" title="Manuell zugeordnet"><svg width="16" height="16" fill="none"><circle cx="8" cy="8" r="8" fill="#e5e7eb"/><path d="M8 4v4l2 2" stroke="#fff" strokeWidth="1.5" strokeLinecap="round"/></svg>Manuell</span>
                      )}
                    </td>
                    <td className="py-2 px-3">
                      <button
                        className={`px-2 py-1 rounded bg-indigo-50 text-indigo-600 text-xs font-semibold hover:bg-indigo-100 transition flex items-center gap-1 ${copySuccess ? 'animate-pulse' : ''} opacity-0 group-hover:opacity-100`}
                        onClick={() => handleCopy(`${m.old_url?.url} -> ${m.new_url?.url}`)}
                        title="Redirect kopieren"
                      >
                        {copySuccess ? <span>✔️</span> : <span>📋</span>}
                        Copy
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
        {/* Pagination */}
        {totalPages > 1 && (
          <div className="flex justify-center gap-2 mt-6">
            {Array.from({ length: totalPages }, (_, i) => (
              <button
                key={i}
                className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-semibold border transition-all duration-150 ${
                  page === i + 1
                    ? 'bg-indigo-500 text-white border-indigo-500 shadow'
                    : 'bg-gray-100 text-gray-500 border-gray-200 hover:bg-indigo-50 hover:text-indigo-600'
                }`}
                onClick={() => setPage(i + 1)}
              >
                {i + 1}
              </button>
            ))}
          </div>
        )}
      </div>
      <div className="w-full flex justify-end px-2 md:px-8 mt-4">
        <button
          className="px-3 py-1 rounded bg-gray-100 text-gray-500 text-xs font-semibold hover:bg-indigo-100 hover:text-indigo-600 border border-gray-200"
          onClick={() => setShowDebug(v => !v)}
        >
          {showDebug ? 'Debug ausblenden' : 'Debug anzeigen'}
        </button>
      </div>
      {showDebug && (
        <div className="w-full px-2 md:px-8 mt-2">
          <pre className="bg-gray-900 text-green-200 rounded p-4 text-xs overflow-x-auto max-h-96">
            {JSON.stringify(redirects, null, 2)}
          </pre>
        </div>
      )}
      {/* Footer Branding */}
      <footer className="mt-8 text-center text-xs text-gray-400 flex flex-col items-center gap-1 w-full px-2 md:px-8">
        <span>Powered by <span className="font-semibold text-indigo-500">OpenAI</span> & modern SaaS-UX</span>
        <a href="#" className="underline hover:text-indigo-600">Datenschutz</a>
      </footer>
      <style jsx>{`
        .sticky-header thead {
          position: sticky;
          top: 0;
          z-index: 10;
        }
        .sticky-header th {
          background: white;
        }
      `}</style>
    </div>
  );
}

function StatCard({ label, value, badge, confidence, icon, tooltip }: { label: string; value: string | number; badge?: string; confidence?: number; icon?: React.ReactNode; tooltip?: string }) {
  return (
    <div className="bg-white rounded-xl shadow p-4 flex flex-col items-center border border-gray-100 relative transition hover:shadow-lg hover:-translate-y-1 group">
      <div className="text-2xl font-bold text-indigo-600 mb-1 flex items-center gap-1">{icon}{value}</div>
      <div className="text-xs text-gray-500 font-medium tracking-wide">{label}</div>
      {badge && (
        <span className={`absolute top-2 right-2 px-2 py-0.5 rounded text-xs font-semibold
          ${badge === 'Exact' ? 'bg-emerald-100 text-emerald-700' : badge === 'Fuzzy' ? 'bg-yellow-100 text-yellow-700' : 'bg-gray-100 text-gray-500'}`}>{badge}</span>
      )}
      {confidence !== undefined && (
        <div className="w-20 h-2 bg-gray-200 rounded mt-2" title={tooltip}>
          <div className="h-2 rounded bg-gradient-to-r from-emerald-400 via-yellow-400 to-pink-400" style={{ width: `${confidence}%` }} />
        </div>
      )}
    </div>
  );
} 